## You should change each of the following fields
## to customize your blog

title: "Data Science Blog"
description: "Welcome to my blog! This is a space dedicated to exploring the realm of data science. Here, I share insights and tutorials on various topics including data analysis, visualization, and statistical modeling. My goal with this blog is to demonstrate how data can be used to drive informed decision-making." 
author: Lauren Scarzella
author_description: "I am a Statistics major at Brigham Young University with an emphasis in Data Science, set to graduate by April 2025. My skills include data cleaning, data visualization, statistical modeling and proficiency in Python and R. I am passionate about transforming data into meaningful and actionable results for real-world impact. I am excited for any opportunities to make use of my skills in data analysis to support more informed decision making." 

url: https://laurenscarzella.github.io ## change this to https://yourusername.github.io
baseurl: /my-blog ## change this to the name of your blog repository
header_image: /assets/img/IMG_2060.JPG ## change your header image if you want

## Add your social media user names.  Github is required, the rest are optional
social:
    github: laurenscarzella
    twitter: 
    facebook: 
    email: scarzellalauren@gmail.com
    linkedin: lauren-scarzella
    youtube: 
    tumblr: 
    website: 



### Advanced Settings (don't change below unless you know what you are doing)

paginate_path: "blog/page:num/"
permalink: blog/:title/

# Header Option
# header: large

sass:
    style: compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Home
      url: /index.html
    - title: About
      url: /about




